Adorn.Web/Areas/ProductManage/Controllers/SubjectComplaintsController.cs
using Adorn.Code;
using Adorn.Domain.Entity.ProductManage;
using Adorn.Application.ProductManage;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Adorn.Web.Areas.ProductManage.Controllers
{
    public class SubjectComplaintsController : BaseController
    {
        private SubjectComplaintsApp _SubjectComplaintsApp = new SubjectComplaintsApp();
        [HttpGet]
        public ActionResult GetTreeSelectJson()
        {
            var data = _SubjectComplaintsApp.GetList();
            var treeList = new List<TreeSelectModel>();
            foreach (var item in data)
            {
                TreeSelectModel treeModel = new TreeSelectModel();
                treeModel.id = item.F_Id;
                treeModel.text = item.F_EnCode;
                treeModel.parentId ="0";
                treeModel.data = item;
                treeList.Add(treeModel);
            }
            return Content(treeList.TreeSelectJson());
        }
        [HttpGet]
        public ActionResult GetTreeGridJson()
        {
            var data = _SubjectComplaintsApp.GetList();
            var treeList = new List<TreeGridModel>();
            foreach (var item in data)
            {
                TreeGridModel treeModel = new TreeGridModel();
                treeModel.id = item.F_Id;
                treeModel.text = item.F_EnCode;
                treeModel.parentId = "0";
                treeModel.expanded = true;
                treeModel.entityJson = item.ToJson();
                treeList.Add(treeModel);
            }
            return Content(treeList.TreeGridJson());
        }



        [HttpGet]
        public ActionResult GetFormJson(string keyValue)
        {
            var data = _SubjectComplaintsApp.GetForm(keyValue);
            return Content(data.ToJson());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitForm(SubjectComplaintsEntity eSubjectComplaintsEntity, string keyValue)
        {
            
            _SubjectComplaintsApp.SubmitForm(eSubjectComplaintsEntity, keyValue);
            return Content("OperationSuccess");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteForm(string keyValue)
        {
            _SubjectComplaintsApp.DeleteForm(keyValue);
            return Content("DeleSuccess");
        }
    }
}

Adorn.Web/Areas/ProductManage/Views/SubjectComplaints/Form.cshtml
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Form.cshtml";
}
<script>
    var keyValue = $.request("keyValue");
    $(function () {
        initControl();
        if (!!keyValue) {
            $.ajax({
                url: "@Url.Action("GetFormJson", "SubjectComplaints")",//,
                data: { keyValue: keyValue },
                dataType: "json",
                async: false,
                cache: false,
                success: function (data) {
                    $("#form1").formSerialize(data);
                }
            });
        }
    });

    function initControl() {

    }
    function submitForm() {
        if (!$('#form1').formValid()) {
            return false;
        }
        $.submitForm({
            url: "@Url.Content("~/ProductManage/SubjectComplaints/SubmitForm")?keyValue=" + keyValue,
            param: $("#form1").formSerialize(),
            success: function () {
                //$.currentWindow().$("#gridList").resetSelection();
                //$.currentWindow().$("#gridList").trigger("reloadGrid");
                $.currentWindow().$("#gridList").bootstrapTable('refresh');
                $.loading(false);
            }
        })
    }
</script>

<form id="form1">
    <div style="padding-top: 20px; margin-right: 20px;">
        <table class="form">
            <tr>
<th class="formTitle" valign="top" style="padding - top: 5px; ">主键</ th > 
<td class="formValue">< input id = "F_Id" name = "F_Id" maxlength = "20" type = "text" class="form-control required" placeholder="请输入" /><label for="F_EnabledMark">有效</label></td>
</tr>

        </table>
    </div>
</form>

Adorn.Web/Areas/ProductManage/Views/SubjectComplaints/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Index.cshtml";
}
<script>
    $(function () {
        $.support.cors = true;
        var oTable = new TableInit();
        oTable.Init();  
    })
    var TableInit = function () {

        var oTableInit = new Object();

        /*初始化Table*/

        oTableInit.Init = function () {

            $('#gridList').dataGrid({
                height: $(window).height() - 96,
                url: "@Url.Action("GetTreeGridJson", "SubjectComplaints")",// ,         //请求后台的URL（*）
                method: 'get',                      //请求方式（*）
                //toolbar: '#bstoolbar',                //工具按钮用哪个容器
                //striped: true,                      //是否显示行间隔色
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                pagination: false,                   //是否显示分页（*）
                //sortable: true,                     //是否启用排序
                //sortOrder: "asc",                   //排序方式
                //传递参数（*）
                queryParams: function (params) { return { keyword: $("#txt_keyword").val() }; },
                //showExport: true,                     //是否显示导出
                //exportDataType: "basic",              //basic', 'all', 'selected'.
                sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                pageNumber: 1,                       //初始化加载第一页，默认第一页
                pageSize: 10,                       //每页的记录行数（*）
                pageList: [10, 25],        //可供选择的每页的行数（*）
                //search: true,                       //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
                //strictSearch: true,
                //showColumns: false,                  //是否显示所有的列
                //showRefresh: true,                  //是否显示刷新按钮
                //minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                //height: 500,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                uniqueId: "F_Id",                     //每一行的唯一标识，一般为主键列
                //showToggle: true,                    //是否显示详细视图和列表视图的切换按钮
                //cardView: false,                    //是否显示详细视图
                //detailView: true,                   //是否显示父子表
                treeGrid: true,
                treeGridMainID: "F_Id",
                treeGridParentID: "F_ParentId",
                sortName: "",
                columns: [
                   { radio: true },
				   { title: '主键', field: 'F_Id', align: 'center'  , visible: false}
{ title: '编码', field: 'F_EnCode', align: 'center'  }
{ title: '名称', field: 'F_FullName', align: 'center'  }
{ title: '区域', field: 'F_Context', align: 'center'  }
{ title: '类型', field: 'F_SubjectId', align: 'center'  }
{ title: '装修的那个流程', field: 'F_ProcessType', align: 'center'  }
{ title: '那个区域', field: 'F_Area', align: 'center'  }
{ title: '状态', field: 'F_Status', align: 'center'  }
{ title: '所属负责人', field: 'F_OwnerId', align: 'center'  }
{ title: '显示列表图', field: 'F_Image', align: 'center'  }
{ title: '小图', field: 'F_MInImage', align: 'center'  }
{ title: '详细图1', field: 'F_MaxImage01', align: 'center'  }
{ title: '详细图2', field: 'F_MaxImage02', align: 'center'  }
{ title: '详细图3', field: 'F_MaxImage03', align: 'center'  }
{ title: '详细图4', field: 'F_MaxImage04', align: 'center'  }
{ title: '', field: 'F_DeleteMark', align: 'center'  }
 { title:'有效', field: 'F_EnabledMark', align: 'center', width: '60', 
formatter: function (value, row, index) {
if (value == 1) { return '<i class="fa fa-toggle-on"></i>'; }else{ return '<i class="fa fa-toggle-off"></i>'; }
 } },
{ title: '', field: 'F_CreatorTime', align: 'center'  }
{ title: '', field: 'F_CreatorUserId', align: 'center'  }
{ title: '', field: 'F_LastModifyTime', align: 'center'  }
{ title: '', field: 'F_LastModifyUserId', align: 'center'  }
{ title: '', field: 'F_DeleteTime', align: 'center'  }
{ title: '', field: 'F_DeleteUserId', align: 'center'  }
{ title: '创建操作用户名', field: 'F_CreatorUserName', align: 'center'  }
{ title: '删除操作用户', field: 'F_DeleteUserName', align: 'center'  }
{ title: '最后修改操作用户', field: 'F_LastModifyUserName', align: 'center'  }

                ]
            });
            $("#btn_search").click(function () {
                $.currentWindow().$("#gridList").bootstrapTable('refresh');
            });
        }
        return oTableInit;
    }
  
    function btn_add() {
        $.modalOpen({
            id: "Form",
            title: "新增",
            url: "@Url.Content("~/ProductManage/SubjectComplaints/Form")",
            width: "450px",
            height: "450px",
            callBack: function (iframeId) {
                top.frames[iframeId].submitForm();
            }
        });
    }
    function btn_edit() {
        var keyValue = $.parseJSON(JSON.stringify($("#gridList").bootstrapTable('getSelections')))[0].F_Id;
        $.modalOpen({
            id: "Form",
            title: "编辑",
            url: "@Url.Content("~/ProductManage/SubjectComplaints/Form")?keyValue=" + keyValue,
            width: "450px",
            height: "450px",
            callBack: function (iframeId) {
                top.frames[iframeId].submitForm();
            }
        });
    }
    function btn_delete() {
        $.deleteForm({
            url: "@Url.Content("~/ProductManage/SubjectComplaints/DeleteForm")",
            param: { keyValue: $.parseJSON(JSON.stringify($("#gridList").bootstrapTable('getSelections')))[0].F_Id },
            success: function () {
                //$.currentWindow().$("#gridList").resetSelection();
                //$.currentWindow().$("#gridList").trigger("reloadGrid");
                $.currentWindow().$("#gridList").bootstrapTable('refresh');
            }
        })
    }

 
</script>

<div class="topPanel">
    <div class="search">
        <table>
            <tr>
                <td style="padding-left: 2px;">
                    <div class="input-group">
                        <input id="txt_keyword" type="text" class="form-control" placeholder="请输入" style="width: 200px;">
                        <span class="input-group-btn">
                            <button id="btn_search" type="button" class="btn  btn-primary"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="toolbar">
        <div class="btn-group">
            <a class="btn btn-primary" onclick="$.reload()"><span class="glyphicon glyphicon-refresh"></span></a>
        </div>
        <div class="btn-group">
            <a id="NF-add" authorize="yes" class="btn btn-primary" onclick="btn_add()"><i class="fa fa-plus"></i>新增</a>
        </div>
        <div class="operate">
            <ul class="nav nav-pills">
                <li class="first">已选中<span>1</span>项</li>
                <li><a id="NF-edit" authorize="yes" onclick="btn_edit()"><i class="fa fa-pencil-square-o"></i>编辑</a></li>
                <li><a id="NF-delete" authorize="yes" onclick="btn_delete()"><i class="fa fa-trash-o"></i>删除</a></li>
            </ul>
            <a href="javascript:;" class="close"></a>
        </div>
        <script>$('.toolbar').authorizeButton()</script>
    </div>
</div>
<div class="gridPanel">
    <table id="gridList"></table>
</div>